# Generated by Django 4.0.4 on 2022-06-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogmodel_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='autor',
            field=models.CharField(max_length=20),
        ),
    ]
