# Generated by Django 4.0.4 on 2022-06-24 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_alter_blogmodel_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.fields.AutoField, to=settings.AUTH_USER_MODEL),
        ),
    ]
