# Generated by Django 4.0.4 on 2022-06-24 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_alter_blogmodel_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('tarea', models.TextField()),
                ('fecha_creacion2', models.DateField(auto_now_add=True)),
                ('autor2', models.ForeignKey(on_delete=django.db.models.fields.AutoField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
