# Generated by Django 4.0.4 on 2022-06-24 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0008_remove_blogmodel2_autor2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel2',
            name='autor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.AutoField, to=settings.AUTH_USER_MODEL),
        ),
    ]
