# Generated by Django 4.0.4 on 2022-06-20 01:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_alter_avatar_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='Avatares',
        ),
    ]
